### ISSUE TITLE
Unicode Error while calling convert function

### ISSUE THREAD

**Issue by MurthyAvanithsa** [senko/python-video-converter#50]
When i was trying to covert a WMV file it shows this error

Traceback (most recent call last):
  File "/virtualenvs/celery/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/virtualenvs/celery/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/virtualenvs/celery/inviterjobs/workers/finalvideo/tasks.py", line 38, in finalvideo
    for timecode in converter_convert:
  File "/virtualenvs/celery/local/lib/python2.7/site-packages/converter/ffmpeg.py", line 453, in convert
    ret = ret.decode(console_encoding)
  File "/virtualenvs/celery/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 9: unexpected end of data

**Comment by mauricioabreu** [comment]
Show what you have done.
What was the command you issued?
