### ISSUE TITLE
converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg

### ISSUE THREAD

**Issue by yashkoli44** [senko/python-video-converter#68]
This is the following stack trace when I run the script:

```
Traceback (most recent call last):
  File "convo.py", line 2, in <module>
    c = Converter()
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python38\lib\site-packages\converter\__init__.py", line 26, in __init__
    self.ffmpeg = FFMpeg(ffmpeg_path=ffmpeg_path,
  File "C:\Users\Yash\AppData\Local\Programs\Python\Python38\lib\site-packages\converter\ffmpeg.py", line 345, in __init__
    raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg
```

**Comment by mattheward** [comment]
I believe the problem you are having is because you do not have ffmpeg installed. 

You can install it here: [https://ffmpeg.org/download.html](url)
